baseURL = "http://example.org/"
title = "Osprey Example Site"
tags = ["portfolio", "web design"]
languageCode = "en-UK"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = " Example Site"
    author = "Avtar Sandhu"
    description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA."
    logoBig = "/images/osprey-logo.png"
    logoSmall = "/images/osprey-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "TomaNistor"
    linkedin = "tomanistor"
    github = "tomanistor"
    facebook = ""
    email = ""
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

    [[menu.main]]
        name = "About"
        url  = "/#about"
        weight = 1
    [[menu.main]]
        name = "Work"
        url  = "/#work"
        weight = 2
    [[menu.main]]
        name = "Contact"
        url  = "/#contact"
        weight = 3
